# Generated by Django 3.2.3 on 2021-05-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='time_end',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='time_start',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='price',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
